(()=>{
'use strict';
const canvas=document.querySelector('#universe');if(!canvas)return;const ctx=canvas.getContext('2d');if(!ctx)return;
const reduced=matchMedia('(prefers-reduced-motion: reduce)');
const layers=[{id:'inicio',name:'NÚCLEO',desc:'O ponto de partida da sua marca.',radius:0,size:2.4,color:[198,255,100],speed:0,phase:0},{id:'estrategia',name:'ESTRATÉGIA',desc:'Uma direção para cada movimento.',radius:8,size:.92,color:[177,157,255],speed:.115,phase:.4},{id:'identidade',name:'IDENTIDADE',desc:'Personalidade em cada ponto de contato.',radius:13,size:1.24,color:[86,213,234],speed:.082,phase:2.1},{id:'digital',name:'DIGITAL',desc:'Experiências que conectam pessoas.',radius:18,size:1.02,color:[255,178,99],speed:.062,phase:4.15},{id:'briefing',name:'SEU PROJETO',desc:'Sua ideia ganha um novo universo.',radius:24,size:1.05,color:[245,131,191],speed:.043,phase:5.25}];
let W=1,H=1,time=0,last=0,active=Number(document.body.dataset.sceneLayer||0),desiredLayer=active,scrollPhase=active,yawOffset=0,zoom=1,overview=false,running=!reduced.matches,drag=null,dragDistance=0,clickTargets=[],cameraYaw=.55,cameraDistance=36,cameraTarget=[0,0,0],centerX=.67,announceTimer;
let seed=127;const random=()=>{seed=(seed*16807)%2147483647;return(seed-1)/2147483646};
const stars=Array.from({length:430},()=>({x:(random()-.5)*180,y:(random()-.5)*130,z:(random()-.5)*180,s:random()*1.2+.5,a:random()*.65+.25}));
const dust=Array.from({length:70},()=>({angle:random()*Math.PI*2,radius:6+random()*21,y:(random()-.5)*.4,size:random()*.025+.015}));
const mix=(a,b,t)=>a+(b-a)*t,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));const $=id=>document.getElementById(id);
function resize(){W=innerWidth;H=innerHeight;const d=Math.min(devicePixelRatio||1,2);canvas.width=W*d;canvas.height=H*d;ctx.setTransform(d,0,0,d,0,0)}addEventListener('resize',resize);resize();
function ui(){const l=layers[active];const status=$('flight-status');if(status)status.textContent='0'+(active+1)+' / '+l.name;const annotation=$('orbit-annotation');if(annotation){annotation.replaceChildren();const strong=document.createElement('strong');strong.textContent=l.name;annotation.append(strong,document.createTextNode(l.desc))}document.querySelectorAll('[data-orbit]').forEach(a=>a.setAttribute('aria-current',String(Number(a.dataset.orbit)===active)));const motion=$('motion');if(motion){motion.textContent=running?'Pausar':'Animar';motion.setAttribute('aria-pressed',String(running))}if($('overview')){$('overview').textContent=overview?'Voltar à órbita':'Ver sistema';$('overview').setAttribute('aria-pressed',String(overview))}clearTimeout(announceTimer);announceTimer=setTimeout(()=>{if($('scene-status'))$('scene-status').textContent='Camada '+l.name+(overview?', visão geral do sistema':'')},200)}
function readScroll(){const sections=[...document.querySelectorAll('[data-layer]')];if(!sections.length){scrollPhase=clamp(Number(document.body.dataset.sceneLayer||0)+scrollY/Math.max(innerHeight*5,1),0,4);return}const at=scrollY+innerHeight*.5;const anchors=sections.map(el=>({el,y:scrollY+el.getBoundingClientRect().top+el.offsetHeight*.5}));let a=anchors[0],b=a;for(const anchor of anchors){if(anchor.y<=at)a=anchor;else{b=anchor;break}b=anchor}const aIndex=Number(a.el.dataset.layer),bIndex=Number(b.el.dataset.layer);scrollPhase=aIndex===bIndex?aIndex:mix(aIndex,bIndex,clamp((at-a.y)/Math.max(1,b.y-a.y),0,1));desiredLayer=clamp(Math.round(scrollPhase),0,4);if(active!==desiredLayer){active=desiredLayer;ui()}}
addEventListener('scroll',readScroll,{passive:true});addEventListener('resize',readScroll);readScroll();ui();
function goToLayer(index){index=clamp(Math.round(index),0,4);const section=$(layers[index].id);if(section){overview=false;active=index;desiredLayer=index;ui();section.scrollIntoView({behavior:reduced.matches?'instant':'smooth',block:'start'})}else location.href='/#'+layers[index].id}
document.querySelectorAll('[data-orbit]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();goToLayer(Number(a.dataset.orbit))}));
function on(id,fn){const b=$(id);if(b)b.addEventListener('click',fn)}on('rotate-left',()=>yawOffset-=Math.PI/6);on('rotate-right',()=>yawOffset+=Math.PI/6);on('zoom-in',()=>zoom=clamp(zoom*.82,.55,1.6));on('zoom-out',()=>zoom=clamp(zoom/ .82,.55,1.6));on('overview',()=>{overview=!overview;zoom=1;ui()});on('motion',()=>{running=!running;ui()});reduced.addEventListener('change',e=>{running=!e.matches;ui()});
canvas.addEventListener('pointerdown',e=>{if(e.button!==0)return;drag={x:e.clientX,y:e.clientY,id:e.pointerId};dragDistance=0;canvas.setPointerCapture(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(!drag)return;const dx=e.clientX-drag.x;const dy=e.clientY-drag.y;dragDistance+=Math.abs(dx)+Math.abs(dy);yawOffset+=dx*.006;drag.x=e.clientX;drag.y=e.clientY});canvas.addEventListener('pointerup',e=>{if(!drag)return;if(dragDistance<8){let hit=clickTargets.filter(p=>Math.hypot(p.x-e.clientX,p.y-e.clientY)<Math.max(26,p.r)).sort((a,b)=>a.z-b.z)[0];if(hit)goToLayer(hit.index)}drag=null});canvas.addEventListener('pointercancel',()=>drag=null);
function pos(layer){const a=layer.phase+time*layer.speed;return [Math.cos(a)*layer.radius,Math.sin(a*2)*.4,Math.sin(a)*layer.radius]}
function basis(eye,target){let f=target.map((v,i)=>v-eye[i]);let len=Math.hypot(...f);f=f.map(x=>x/len);let r=[-f[2],0,f[0]];len=Math.hypot(...r);r=r.map(x=>x/len);const u=[r[1]*f[2]-r[2]*f[1],r[2]*f[0]-r[0]*f[2],r[0]*f[1]-r[1]*f[0]];return{f,r,u}}
function project(p,eye,b){const q=p.map((v,i)=>v-eye[i]),dot=v=>q.reduce((s,x,i)=>s+x*v[i],0),z=dot(b.f);if(z<.5)return null;const scale=H*.86/z;return{x:W*centerX+dot(b.r)*scale,y:H*(W<600?.30:.49)-dot(b.u)*scale,z,scale}}
function rgba(c,a){return 'rgba('+c.join(',')+','+a+')'}
function sphere(p,size,color,index){const r=Math.max(2,size*p.scale);const glow=ctx.createRadialGradient(p.x,p.y,0,p.x,p.y,r*3.8);glow.addColorStop(0,rgba(color,index===0?.22:.12));glow.addColorStop(1,rgba(color,0));ctx.fillStyle=glow;ctx.beginPath();ctx.arc(p.x,p.y,r*3.8,0,Math.PI*2);ctx.fill();const fill=ctx.createRadialGradient(p.x-r*.4,p.y-r*.4,r*.04,p.x,p.y,r);fill.addColorStop(0,'#f2fff5');fill.addColorStop(.17,rgba(color,1));fill.addColorStop(.62,rgba(color,.88));fill.addColorStop(1,'#060b17');ctx.fillStyle=fill;ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle=rgba(color,.4);ctx.lineWidth=.7;ctx.stroke();if(index===active){ctx.strokeStyle=rgba(color,.65);ctx.lineWidth=1;ctx.setLineDash([3,5]);ctx.beginPath();ctx.arc(p.x,p.y,r+10,0,Math.PI*2);ctx.stroke();ctx.setLineDash([])}if(W>600||index===active){ctx.font='14px monospace';ctx.textAlign='center';ctx.fillStyle=index===active?'#eff7e9':'#b8c3d2';ctx.fillText(layers[index].name,p.x,p.y+r+30)}clickTargets.push({x:p.x,y:p.y,r:r+12,z:p.z,index})}
function frame(now){const dt=clamp((now-last)/1000,0,.05);last=now;if(document.hidden){requestAnimationFrame(frame);return}if(running)time+=dt;const ease=reduced.matches?1:1-Math.exp(-dt*4);const i=Math.floor(scrollPhase),j=Math.min(4,i+1),weight=scrollPhase-i;const focus=pos(layers[i]).map((v,k)=>mix(v,pos(layers[j])[k],weight));const focusFactor=overview?0:.5;cameraTarget=cameraTarget.map((v,k)=>mix(v,focus[k]*focusFactor,ease));const desiredYaw=.55+scrollPhase*.58+yawOffset+(running?time*.012:0);cameraYaw=mix(cameraYaw,desiredYaw,ease);const desiredDistance=(overview?72:36)*zoom;cameraDistance=mix(cameraDistance,desiredDistance,ease);const contentOnRight=active===2&&document.body.classList.contains('home');const desiredCenter=W<600?.5:contentOnRight?.29:.68;centerX=mix(centerX,desiredCenter,ease);const elevation=overview?.86:.52;const eye=[cameraTarget[0]+Math.cos(cameraYaw)*cameraDistance*Math.cos(elevation),cameraTarget[1]+cameraDistance*Math.sin(elevation),cameraTarget[2]+Math.sin(cameraYaw)*cameraDistance*Math.cos(elevation)];const b=basis(eye,cameraTarget);ctx.clearRect(0,0,W,H);const atmosphere=ctx.createRadialGradient(W*centerX,H*.45,0,W*centerX,H*.45,Math.max(W,H)*.7);atmosphere.addColorStop(0,'#102131');atmosphere.addColorStop(.6,'#060c19');atmosphere.addColorStop(1,'#03050c');ctx.fillStyle=atmosphere;ctx.fillRect(0,0,W,H);
for(const star of stars){const p=project([star.x,star.y,star.z],eye,b);if(!p||p.x<0||p.x>W||p.y<0||p.y>H)continue;ctx.fillStyle='rgba(208,226,255,'+star.a+')';ctx.beginPath();ctx.arc(p.x,p.y,star.s,0,Math.PI*2);ctx.fill()}
let objects=[];clickTargets=[];for(let index=1;index<layers.length;index++){const l=layers[index];for(let n=0;n<120;n++){const a=n/120*Math.PI*2,c=(n+1)/120*Math.PI*2;const p=project([Math.cos(a)*l.radius,0,Math.sin(a)*l.radius],eye,b),q=project([Math.cos(c)*l.radius,0,Math.sin(c)*l.radius],eye,b);if(p&&q)objects.push({type:'line',p,q,z:(p.z+q.z)/2,color:l.color,active:index===active})}}
for(const part of dust){const a=part.angle+time*.023;const p=project([Math.cos(a)*part.radius,part.y,Math.sin(a)*part.radius],eye,b);if(p)objects.push({type:'dust',p,z:p.z,size:part.size})}
layers.forEach((l,index)=>{const p=project(pos(l),eye,b);if(p)objects.push({type:'sphere',p,z:p.z,l,index});if(index>0){const lp=pos(l),a=time*.7+index;const p=project([lp[0]+Math.cos(a)*1.7,lp[1]+.2,lp[2]+Math.sin(a)*1.7],eye,b);if(p)objects.push({type:'moon',p,z:p.z})}});objects.sort((a,b)=>b.z-a.z);for(const o of objects){if(o.type==='line'){ctx.strokeStyle=rgba(o.color,o.active?.36:.12);ctx.lineWidth=o.active?1.2:.65;ctx.beginPath();ctx.moveTo(o.p.x,o.p.y);ctx.lineTo(o.q.x,o.q.y);ctx.stroke()}else if(o.type==='sphere')sphere(o.p,o.l.size,o.l.color,o.index);else{ctx.fillStyle=o.type==='moon'?'#b3c4d6':'#a5b9d366';ctx.beginPath();ctx.arc(o.p.x,o.p.y,Math.max(.6,o.p.scale*(o.size||.14)),0,Math.PI*2);ctx.fill()}}
requestAnimationFrame(frame)}requestAnimationFrame(frame);
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'configure_orbit_view',description:'Ajustar a visão 3D: girar, aproximar, pausar ou visualizar todo o sistema orbital.',inputSchema:{type:'object',properties:{rotation:{type:'number',minimum:-360,maximum:360},zoom:{type:'number',minimum:.55,maximum:1.6},overview:{type:'boolean'},running:{type:'boolean'}},additionalProperties:false},execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).some(k=>!['rotation','zoom','overview','running'].includes(k)))throw new Error('Configuração inválida');if(input.rotation!==undefined&&(!Number.isFinite(input.rotation)||Math.abs(input.rotation)>360))throw new Error('Rotação inválida');if(input.zoom!==undefined&&(!Number.isFinite(input.zoom)||input.zoom<.55||input.zoom>1.6))throw new Error('Zoom inválido');for(const k of ['overview','running'])if(input[k]!==undefined&&typeof input[k]!=='boolean')throw new Error('Esperado valor booleano');if(input.rotation!==undefined)yawOffset=input.rotation*Math.PI/180;if(input.zoom!==undefined)zoom=input.zoom;if(input.overview!==undefined)overview=input.overview;if(input.running!==undefined)running=input.running;ui();return{layer:layers[active].name,rotation:yawOffset*180/Math.PI,zoom,overview,running}}})).catch(()=>{})}catch(e){}}
})();
